#!/bin/bash

if [[ "$#" -gt 0 ]]; then
	dirs="$1"
else
	dirs=(pdb_raw pdb_prepped pdb_aligned pdb_cappings)
fi

for dir in "${dirs[@]}"
do
    base=$(basename "$dir")
    echo "Compressing $dir"
    tar -cjSf "${base}.tar.bz2" "$dir"
done

echo "Done."
