#!/bin/bash

PYTHON=python3
echo "Using PYTHON=${PYTHON}"

git clone https://github.com/joy13975/elfin

rm -rf ./elfinpy
ln -s ./elfin/elfinpy ./elfinpy
ln -s ./elfin/activate activate

virtualenv --python=$PYTHON .venv
. ./activate

python3 -m pip install -r elfin/requirements.txt