#!/bin/bash
# Exit venv if user did not do so
if [[ ! -z "$VIRTUAL_ENV" ]]; then
	echo "You're in virtualenv. Please run deactivate first"
	exit 1
fi

PYTHON=python3
echo "Using PYTHON=${PYTHON}"
# link the right repositiories! (link the branches I produce!! ) my-calc-branch \
rm -rf elfinpy misc metadata activate
echo 'Fetching files...'

svn export https://github.com/Parmeggiani-Lab/elfin/trunk/elfinpy
svn export https://github.com/Parmeggiani-Lab/elfin/trunk/requirements.txt
svn export https://github.com/Parmeggiani-Lab/elfin/trunk/misc
svn export https://github.com/Parmeggiani-Lab/elfin/trunk/activate
svn export https://github.com/Parmeggiani-Lab/Library_01/trunk/metadata
svn export https://github.com/Parmeggiani-Lab/elfin/trunk/pymol_scripts

venv_dir=".venv"
if [[ ! -d "$venv_dir" ]]; then
	virtualenv --python=$PYTHON $venv_dir
fi
. ./activate

python3 -m pip install -r requirements.txt
